"""Add extra queue cols

Revision ID: 33ab87fce864
Revises: 442dad51aca2
Create Date: 2018-01-28 13:17:54.172488

"""

# revision identifiers, used by Alembic.
revision = '33ab87fce864'
down_revision = '442dad51aca2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ### server_default=sa.text(u"'0'")
    op.alter_column('phone_queue', 'synced',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text(u'false'))
    op.alter_column('queues', 'deleted',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    existing_server_default=sa.text(u'false'))
    op.drop_index('ix_phone_queue_sent', table_name='phone_queue')
    op.add_column('queues', sa.Column('branch_name', sa.String(length=45), nullable=True))
    op.add_column('queues', sa.Column('completed', sa.Boolean(), nullable=False, server_default=sa.text(u'false')))
    op.add_column('queues', sa.Column('selected', sa.Boolean(), nullable=False, server_default=sa.text(u'false')))
    op.add_column('queues', sa.Column('synced', sa.Boolean(), nullable=False, server_default=sa.text(u'false')))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'synced')
    op.drop_column('queues', 'selected')
    op.drop_column('queues', 'completed')
    op.drop_column('queues', 'branch_name')
    op.create_index('ix_phone_queue_sent', 'phone_queue', ['sent'], unique=False)
    op.alter_column('phone_queue', 'synced',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text(u'false'))
    op.alter_column('queues', 'deleted',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    existing_server_default=sa.text(u'false'))
    ### end Alembic commands ###
