"""add more columns to the queue

Revision ID: 442dad51aca2
Revises: 186a18f93ba0
Create Date: 2017-12-07 07:28:59.564103

"""

# revision identifiers, used by Alembic.
revision = '442dad51aca2'
down_revision = '186a18f93ba0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_queue', sa.Column('assigned_to', sa.String(length=45), nullable=True))
    op.add_column('phone_queue', sa.Column('phone_id', sa.Integer(), nullable=True))
    op.add_column('phone_queue', sa.Column('synced', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_phone_queue_phone_id'), 'phone_queue', ['phone_id'], unique=False)
    op.create_foreign_key(None, 'phone_queue', 'phones', ['phone_id'], ['id'])
    op.add_column('ussd_messages', sa.Column('queue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ussd_messages', 'phones', ['queue_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ussd_messages', type_='foreignkey')
    op.drop_column('ussd_messages', 'queue_id')
    op.drop_constraint(None, 'phone_queue', type_='foreignkey')
    op.drop_index(op.f('ix_phone_queue_phone_id'), table_name='phone_queue')
    op.drop_column('phone_queue', 'phone_id')
    op.drop_column('phone_queue', 'assigned_to')
    op.drop_column('phone_queue', 'synced')
    ### end Alembic commands ###
