"""Use Country are FK

Revision ID: 45728000f809
Revises: 4db5404fea7a
Create Date: 2017-11-06 14:22:15.171169

"""

# revision identifiers, used by Alembic.
revision = '45728000f809'
down_revision = '4db5404fea7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'country')
    op.add_column(u'queues', sa.Column('country', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_queues_country'), 'queues', ['country'], unique=False)
    op.create_foreign_key(None, 'queues', 'geos', ['country'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'queues', type_='foreignkey')
    op.drop_index(op.f('ix_queues_country'), table_name='queues')
    op.add_column(u'queues', sa.Column('country', sa.String(length=45), nullable=True))
    ### end Alembic commands ###
