"""Add date_added cols to tables

Revision ID: 4db5404fea7a
Revises: 56fb768102cc
Create Date: 2017-10-18 14:18:53.804053

"""

# revision identifiers, used by Alembic.
revision = '4db5404fea7a'
down_revision = '56fb768102cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_queue', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('phones', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('queues', sa.Column('date_added', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'date_added')
    op.drop_column('phones', 'date_added')
    op.drop_column('phone_queue', 'date_added')
    ### end Alembic commands ###
