"""Add queue names and relationships

Revision ID: 56fb768102cc
Revises: 158fa87545d8
Create Date: 2017-10-18 14:12:54.074893

"""

# revision identifiers, used by Alembic.
revision = '56fb768102cc'
down_revision = '158fa87545d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=45), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], [u'branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queues_branch_id'), 'queues', ['branch_id'], unique=False)
    op.create_index(op.f('ix_queues_deleted'), 'queues', ['deleted'], unique=False)
    op.add_column(u'phone_queue', sa.Column('queue_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_phone_queue_queue_id'), 'phone_queue', ['queue_id'], unique=False)
    op.create_foreign_key(None, 'phone_queue', 'queues', ['queue_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phone_queue', type_='foreignkey')
    op.drop_index(op.f('ix_phone_queue_queue_id'), table_name='phone_queue')
    op.drop_column(u'phone_queue', 'queue_id')
    op.drop_index(op.f('ix_queues_deleted'), table_name='queues')
    op.drop_index(op.f('ix_queues_branch_id'), table_name='queues')
    op.drop_table('queues')
    ### end Alembic commands ###
